from datetime import datetime as dt
year=int(input("年:"))
month=int(input("月:"))
day=int(input("日:"))
hour=int(input("时:"))
minute=int(input("分:"))
second=int(input("秒:"))
t1=dt(year,month,day,hour=hour,minute=minute,second=second)
t1=t1.strftime("%Y-%m-%d %H:%M:%S")
print(type(t1))  

# year = int(input("年:"))
# month = int(input("月:"))
# day = int(input("日:"))
# hour = int(input("时:"))
# minute = int(input("分:"))
# second = int(input("秒:"))
# t3 = dt(year, month, day, hour, minute=minute, second=second)
# month = int(input("月:"))
# day = int(input("日:"))
# hour = int(input("时:"))
# minute = int(input("分:"))
# second = int(input("秒:"))
# t2 = dt(year, month, day, hour=hour, minute=minute, second=second)
# print(t1)

# t1=datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")  
t2=dt.now().strftime("%Y-%m-%d %H:%M:%S")  
print(type(t2))
print(t2)